version: '3'
services:
  api:
    build: .
    volumes:
      - ./app:/app
      - socket:/tmp
    command: uwsgi --ini /app/uwsgi.ini

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp

volumes:
  socket:
